'use strict';
import getNonceValue from "./functions/getNonceValue";
import rateExperience from "./functions/reviews/rateExperience";
import storeReview from "./functions/reviews/storeReview";
import requestReview from "./functions/reviewrequests/requestReview";
import getPendingReviews from "./functions/reviewrequests/getPendingReviews";
import updateRegistry from "./functions/registry/updateRegistry";
import getNonceForUpdatingRegistry from "./functions/registry/getNonceForUpdatingRegistry";
import getUserAddress from "./functions/registry/getUserAddress";
import registerAsBusiness from "./functions/api/registerAsBusiness";
import registerAsWorker from "./functions/api/registerAsWorker";
import registerWorkerRewardSystem from "./functions/api/registerWorkerRewardSystem";
import registerAsUser from "./functions/api/registerAsUser";
import addWorker from "./functions/api/addWorker";
import rateBoomerangExperience from "./functions/api/rateBoomerangExperience";

module.exports.getNonceValue = getNonceValue;
module.exports.rateExperience = rateExperience;
module.exports.storeReview = storeReview;
module.exports.requestReview = requestReview;
module.exports.getPendingReviews = getPendingReviews;
module.exports.updateRegistry = updateRegistry;
module.exports.getUserAddress = getUserAddress;
module.exports.getNonceForUpdatingRegistry = getNonceForUpdatingRegistry;
module.exports.registerAsBusiness = registerAsBusiness;
module.exports.registerAsWorker = registerAsWorker;
module.exports.registerAsUser = registerAsUser;
module.exports.registerWorkerRewardSystem = registerWorkerRewardSystem;
module.exports.addWorker = addWorker;
module.exports.rateBoomerangExperience = rateBoomerangExperience;
